# Generated by Django 5.2.6 on 2026-09-27 15:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=8)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit card'), ('investment', 'Investment')], max_length=11)),
                ('scope', models.CharField(choices=[('private', 'Private'), ('household', 'Household')], default='private', max_length=9)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.household')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=8)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('huntington', 'Huntington Bank'), ('capital_one', 'Capital One'), ('apple_card', 'Apple Card'), ('vanguard', 'Vanguard')], max_length=32)),
                ('source_file_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='finance.account')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='finance.person')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounts', to='finance.person'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=8)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('cash_flow', 'Cash flow'), ('investment_activity', 'Investment activity (neutral)')], default='cash_flow', max_length=19)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_transaction_id', models.CharField(blank=True, max_length=255)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('original_fields', models.JSONField(validators=[finance.models.validate_json_object])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='finance.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='finance.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('person',), name='one_current_household_per_person'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('joined_at')), _connector='OR'), name='membership_end_not_before_join')],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('huntington', 'capital_one', 'apple_card', 'vanguard'))), name='import_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('date_range_end__gte', models.F('date_range_start'))), name='import_date_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='import_batch_archive_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('household__isnull', True), ('scope', 'private')), models.Q(('household__isnull', False), ('scope', 'household')), _connector='OR'), name='account_scope_matches_household'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='account_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ('checking', 'savings', 'credit_card', 'investment'))), name='account_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='account_archive_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_date'], name='txn_account_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'source_transaction_id'], name='txn_account_source_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='transaction_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('cash_flow', 'investment_activity'))), name='transaction_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_row_number__gt', 0)), name='transaction_source_row_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='transaction_archive_state_consistent'),
        ),
    ]
