# Generated by Django 5.2.17 on 2026-09-29 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auth_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCorrectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_name', models.CharField(choices=[('transaction_date', 'Date'), ('description', 'Description'), ('amount_minor', 'Amount')], max_length=16)),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('previous_description', models.TextField(blank=True, default='')),
                ('new_description', models.TextField(blank=True, default='')),
                ('previous_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('new_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_correction_history', to='finance.person')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_history', to='finance.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['transaction', 'recorded_at'], name='txn_corr_hist_txn_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('field_name', 'transaction_date'), ('new_amount_minor__isnull', True), ('new_date__isnull', False), ('new_description', ''), ('previous_amount_minor__isnull', True), ('previous_date__isnull', False), ('previous_description', '')), models.Q(('currency', ''), ('field_name', 'description'), ('new_amount_minor__isnull', True), ('new_date__isnull', True), ('previous_amount_minor__isnull', True), ('previous_date__isnull', True)), models.Q(('currency', 'USD'), ('field_name', 'amount_minor'), ('new_amount_minor__isnull', False), ('new_date__isnull', True), ('new_description', ''), ('previous_amount_minor__isnull', False), ('previous_date__isnull', True), ('previous_description', '')), _connector='OR'), name='correction_history_value_shape')],
            },
        ),
    ]
