# Generated by Django 5.2.17 on 2026-09-30 03:11

import django.db.models.deletion
import finance.models
from django.db import migrations, models


STARTER_CUSTOM_NAMES = (
    "Income",
    "Groceries",
    "Dining",
    "Transportation",
    "Housing",
    "Utilities",
    "Health",
    "Insurance",
    "Shopping",
    "Entertainment",
    "Subscriptions",
    "Travel",
    "Education",
    "Personal care",
    "Gifts and donations",
    "Fees and interest",
    "Taxes",
)


def seed_household_categories(apps, schema_editor):
    Household = apps.get_model("finance", "Household")
    Category = apps.get_model("finance", "Category")
    rows = []
    for household in Household.objects.all():
        existing = set(Category.objects.filter(household=household).values_list("name", flat=True))
        if "Uncategorized" not in existing:
            rows.append(Category(household=household, name="Uncategorized", code="uncategorized"))
        if "Transfer" not in existing:
            rows.append(Category(household=household, name="Transfer", code="transfer"))
        for name in STARTER_CUSTOM_NAMES:
            if name not in existing:
                rows.append(Category(household=household, name=name, code="custom"))
    Category.objects.bulk_create(rows)


def unseed_household_categories(apps, schema_editor):
    Category = apps.get_model("finance", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_correction_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(choices=[('custom', 'Custom'), ('uncategorized', 'Uncategorized'), ('transfer', 'Transfer')], default='custom', max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('auto_marked', 'Auto-marked'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('undone', 'Undone')], max_length=11)),
                ('kind', models.CharField(choices=[('transfer', 'Transfer'), ('card_payment', 'Credit-card payment')], max_length=12)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=4)),
                ('reasons', models.JSONField(validators=[finance.models.validate_reason_list])),
                ('leg_a_category_id_at_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('leg_b_category_id_at_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='transactioncorrectionhistory',
            name='correction_history_value_shape',
        ),
        migrations.AddField(
            model_name='household',
            name='transfer_match_window_days',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='transactioncorrectionhistory',
            name='field_name',
            field=models.CharField(choices=[('transaction_date', 'Date'), ('description', 'Description'), ('amount_minor', 'Amount'), ('category', 'Category'), ('exclusion', 'Transfer exclusion'), ('refund_link', 'Refund link')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_match_window_days__lte', 366)), name='household_transfer_window_days_range'),
        ),
        migrations.AddConstraint(
            model_name='transactioncorrectionhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('field_name', 'transaction_date'), ('new_amount_minor__isnull', True), ('new_date__isnull', False), ('new_description', ''), ('previous_amount_minor__isnull', True), ('previous_date__isnull', False), ('previous_description', '')), models.Q(('currency', ''), ('field_name__in', ('description', 'category', 'exclusion', 'refund_link')), ('new_amount_minor__isnull', True), ('new_date__isnull', True), ('previous_amount_minor__isnull', True), ('previous_date__isnull', True)), models.Q(('currency', 'USD'), ('field_name', 'amount_minor'), ('new_amount_minor__isnull', False), ('new_date__isnull', True), ('new_description', ''), ('previous_amount_minor__isnull', False), ('previous_date__isnull', True), ('previous_description', '')), _connector='OR'), name='correction_history_value_shape'),
        ),
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='finance.household'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category'),
        ),
        migrations.AddField(
            model_name='refundlink',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='refundlink',
            name='refund',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_link', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='transferpair',
            name='leg_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_pairs_as_a', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='transferpair',
            name='leg_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_pairs_as_b', to='finance.transaction'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='category_unique_name_per_household'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('code', 'custom'), _negated=True), fields=('household', 'code'), name='category_unique_system_code_per_household'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('code__in', ('custom', 'uncategorized', 'transfer'))), name='category_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='refundlink',
            constraint=models.CheckConstraint(condition=models.Q(('refund', models.F('original')), _negated=True), name='refund_link_distinct_transactions'),
        ),
        migrations.AddConstraint(
            model_name='transferpair',
            constraint=models.CheckConstraint(condition=models.Q(('leg_a_id__lt', models.F('leg_b_id'))), name='transfer_pair_leg_order'),
        ),
        migrations.AddConstraint(
            model_name='transferpair',
            constraint=models.UniqueConstraint(fields=('leg_a', 'leg_b'), name='transfer_pair_unique_legs'),
        ),
        migrations.AddConstraint(
            model_name='transferpair',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('suggested', 'auto_marked', 'confirmed', 'dismissed', 'undone'))), name='transfer_pair_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='transferpair',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('transfer', 'card_payment'))), name='transfer_pair_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='transferpair',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__in', ('high', 'low'))), name='transfer_pair_confidence_valid'),
        ),
        migrations.RunPython(seed_household_categories, unseed_household_categories),
    ]
