# Generated by Django 5.2.17 on 2026-09-30 10:39

import django.core.validators
import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_categories_transfers_refunds'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=9)),
                ('typical_amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('possible', 'Possible'), ('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], max_length=10)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('reasons', models.JSONField(validators=[finance.models.validate_reason_list])),
                ('fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase hexadecimal SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_series', to='finance.person')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringSeriesMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='finance.recurringseries')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_memberships', to='finance.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recurringseries',
            constraint=models.UniqueConstraint(fields=('person', 'fingerprint'), name='recurring_series_person_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='recurringseries',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='recurring_series_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='recurringseries',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('possible', 'suggested', 'confirmed', 'dismissed'))), name='recurring_series_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringseries',
            constraint=models.CheckConstraint(condition=models.Q(('cadence__in', ('weekly', 'biweekly', 'monthly', 'quarterly', 'annual'))), name='recurring_series_cadence_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringseries',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__in', ('high', 'medium', 'low'))), name='recurring_series_confidence_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringseries',
            constraint=models.CheckConstraint(condition=models.Q(('typical_amount_minor__lt', 0)), name='recurring_series_amount_is_charge'),
        ),
        migrations.AddConstraint(
            model_name='recurringseriesmember',
            constraint=models.UniqueConstraint(fields=('series', 'transaction'), name='recurring_member_unique'),
        ),
    ]
