# Generated by Django 5.2.17 on 2026-10-01 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_category_source(apps, schema_editor):
    Transaction = apps.get_model("finance", "Transaction")
    RefundLink = apps.get_model("finance", "RefundLink")
    refund_ids = list(RefundLink.objects.values_list("refund_id", flat=True))
    categorized = Transaction.objects.filter(category_id__isnull=False)
    categorized.filter(pk__in=refund_ids).update(category_source="inherited")
    categorized.exclude(pk__in=refund_ids).update(category_source="manual")


def unfill_category_source(apps, schema_editor):
    Transaction = apps.get_model("finance", "Transaction")
    Transaction.objects.filter(category_source__in=("manual", "inherited")).update(category_source="")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_recurring_series_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_contains', models.CharField(max_length=200)),
                ('min_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('max_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RuleApplicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_category_source', models.CharField(blank=True, default='', max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('manual', 'Manual'), ('rule', 'Rule'), ('inherited', 'Inherited')], default='', max_length=9),
        ),
        migrations.RunPython(backfill_category_source, unfill_category_source),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('category_source__in', ('', 'manual', 'rule', 'inherited'))), name='transaction_category_source_valid'),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_rules', to='finance.account'),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_rules', to='finance.category'),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='owner_household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_rules', to='finance.household'),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_rules', to='finance.person'),
        ),
        migrations.AddField(
            model_name='ruleapplication',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_applications', to='finance.person'),
        ),
        migrations.AddField(
            model_name='ruleapplication',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='finance.categoryrule'),
        ),
        migrations.AddField(
            model_name='ruleapplicationentry',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.ruleapplication'),
        ),
        migrations.AddField(
            model_name='ruleapplicationentry',
            name='previous_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.category'),
        ),
        migrations.AddField(
            model_name='ruleapplicationentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_application_entries', to='finance.transaction'),
        ),
        migrations.AddIndex(
            model_name='categoryrule',
            index=models.Index(fields=['owner_person', 'priority'], name='cat_rule_person_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryrule',
            index=models.Index(fields=['owner_household', 'priority'], name='cat_rule_hh_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_household__isnull', True), ('owner_person__isnull', False)), models.Q(('owner_household__isnull', False), ('owner_person__isnull', True)), _connector='OR'), name='category_rule_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='categoryrule',
            constraint=models.CheckConstraint(condition=models.Q(('description_contains', ''), _negated=True), name='category_rule_description_present'),
        ),
        migrations.AddConstraint(
            model_name='categoryrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount_minor__isnull', True), ('max_amount_minor__isnull', True), ('min_amount_minor__lte', models.F('max_amount_minor')), _connector='OR'), name='category_rule_amount_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='ruleapplicationentry',
            constraint=models.UniqueConstraint(fields=('application', 'transaction'), name='rule_application_entry_unique_txn'),
        ),
        migrations.AddConstraint(
            model_name='ruleapplicationentry',
            constraint=models.CheckConstraint(condition=models.Q(('previous_category_source__in', ('', 'manual', 'rule', 'inherited'))), name='rule_application_prev_source_valid'),
        ),
    ]
