# Generated by Django 5.2.17 on 2026-10-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_recurring_series_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplefin_account_id', models.CharField(max_length=255)),
                ('cutover_date', models.DateField()),
                ('mode', models.CharField(choices=[('transactions', 'Transactions'), ('balances_only', 'Balances only')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source', models.CharField(choices=[('simplefin', 'SimpleFIN'), ('manual', 'Manual')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleFinConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_access_url', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_result', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='import_source_valid',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('huntington', 'Huntington Bank'), ('capital_one', 'Capital One'), ('apple_card', 'Apple Card'), ('vanguard', 'Vanguard'), ('simplefin', 'SimpleFIN')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('huntington', 'capital_one', 'apple_card', 'vanguard', 'simplefin'))), name='import_source_valid'),
        ),
        migrations.AddField(
            model_name='accountlink',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simplefin_link', to='finance.account'),
        ),
        migrations.AddField(
            model_name='balancesnapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='finance.account'),
        ),
        migrations.AddField(
            model_name='balancesnapshot',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_snapshots', to='finance.importbatch'),
        ),
        migrations.AddField(
            model_name='simplefinconnection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simplefin_connections', to='finance.person'),
        ),
        migrations.AddField(
            model_name='accountlink',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='finance.simplefinconnection'),
        ),
        migrations.AddConstraint(
            model_name='balancesnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'snapshot_date', 'source'), name='balance_snapshot_unique_account_date_source'),
        ),
        migrations.AddConstraint(
            model_name='balancesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='balance_snapshot_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='balancesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('simplefin', 'manual'))), name='balance_snapshot_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='accountlink',
            constraint=models.UniqueConstraint(fields=('connection', 'simplefin_account_id'), name='account_link_unique_simplefin_account'),
        ),
        migrations.AddConstraint(
            model_name='accountlink',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ('transactions', 'balances_only'))), name='account_link_mode_valid'),
        ),
    ]
