# Generated by Django 5.2.17 on 2026-10-01 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_account_share_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('private', 'Private'), ('household', 'Household')], default='private', max_length=9)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cadence', models.CharField(choices=[('one_time', 'One-time'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=9)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_items', to='finance.category')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_items', to='finance.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_items', to='finance.person')),
                ('replaces_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_planned_items', to='finance.recurringseries')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('household__isnull', True), ('scope', 'private')), models.Q(('household__isnull', False), ('scope', 'household')), _connector='OR'), name='planned_item_scope_matches_household'), models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='planned_item_currency_usd'), models.CheckConstraint(condition=models.Q(('kind__in', ('income', 'expense'))), name='planned_item_kind_valid'), models.CheckConstraint(condition=models.Q(('cadence__in', ('one_time', 'weekly', 'biweekly', 'monthly', 'quarterly', 'annual'))), name='planned_item_cadence_valid'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='planned_item_amount_positive'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='planned_item_end_on_or_after_start')],
            },
        ),
    ]
