# Generated by Django 5.2.17 on 2026-10-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_simplefin_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesnapshot',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
