# Generated by Django 5.2.17 on 2026-10-02 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_rule_application_reversed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=8)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('private', 'Private'), ('household', 'Household')], default='private', max_length=9)),
                ('name', models.CharField(max_length=150)),
                ('target_amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('target_date', models.DateField()),
                ('manual_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('manual_amount_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_goals', to='finance.household')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_goals', to='finance.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_goals', to='finance.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('household__isnull', True), ('scope', 'private')), models.Q(('household__isnull', False), ('scope', 'household')), _connector='OR'), name='savings_goal_scope_matches_household'), models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='savings_goal_currency_usd'), models.CheckConstraint(condition=models.Q(('target_amount_minor__gt', 0)), name='savings_goal_target_positive'), models.CheckConstraint(condition=models.Q(models.Q(('manual_amount_date__isnull', True), ('manual_amount_minor__isnull', True)), models.Q(('manual_amount_date__isnull', False), ('manual_amount_minor__isnull', False)), _connector='OR'), name='savings_goal_manual_amount_paired_with_date'), models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='savings_goal_archive_state_consistent')],
            },
        ),
    ]
