# Generated by Django 5.2.17 on 2026-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_savings_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesnapshot',
            name='net_contribution_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='balancesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('net_contribution_minor__isnull', True), ('source', 'manual'), _connector='OR'), name='balance_snapshot_contribution_requires_manual'),
        ),
    ]
