# Generated by Django 5.2.17 on 2026-10-02 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_balance_snapshot_net_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('body', models.TextField()),
                ('is_material', models.BooleanField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='privacy_policy_declined_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_by', to='finance.privacypolicyversion'),
        ),
        migrations.CreateModel(
            name='PrivacyPolicyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policy_acceptances', to='finance.person')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='finance.privacypolicyversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'policy_version'), name='privacy_acceptance_unique_person_version')],
            },
        ),
    ]
