# Generated by Django 5.2.17 on 2026-10-02 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('backend', models.CharField(max_length=32)),
                ('feature', models.CharField(max_length=40)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_events', to='finance.person')),
            ],
        ),
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=40)),
                ('backend', models.CharField(blank=True, default='', max_length=32)),
                ('input_refs', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('waiting_model', 'Waiting for model'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_ref', models.CharField(blank=True, default='', max_length=120)),
                ('failure_code', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='finance.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('queued', 'waiting_model', 'running', 'succeeded', 'failed'))), name='ai_job_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='AiProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('agent_harness', 'Agent Harness')], default='agent_harness', max_length=32)),
                ('base_url', models.CharField(max_length=255)),
                ('encrypted_token', models.BinaryField()),
                ('harness_project', models.CharField(blank=True, default='', max_length=80)),
                ('chat_backend', models.CharField(blank=True, default='', max_length=32)),
                ('background_backend', models.CharField(blank=True, default='', max_length=32)),
                ('chat_model', models.CharField(blank=True, default='', max_length=80)),
                ('background_model', models.CharField(blank=True, default='', max_length=80)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_status', models.CharField(blank=True, default='', max_length=80)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_connections', to='finance.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'kind'), name='ai_connection_unique_owner_kind'), models.CheckConstraint(condition=models.Q(('kind__in', ('agent_harness',))), name='ai_connection_kind_valid')],
            },
        ),
    ]
