# Generated by Django 5.2.17 on 2026-10-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_ai_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=32)),
                ("backend", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="finance.category",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_category_suggestions",
                        to="finance.person",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="finance.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="categorysuggestion",
            constraint=models.UniqueConstraint(
                fields=("member", "transaction"),
                name="category_suggestion_unique_member_txn",
            ),
        ),
        migrations.AddConstraint(
            model_name="categorysuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("pending", "accepted", "rejected"))),
                name="category_suggestion_status_valid",
            ),
        ),
    ]
