# Generated by Django 5.2.17 on 2026-10-03 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_category_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.BigIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='ruleapplicationentry',
            name='rule_application_prev_source_valid',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_category_source_valid',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('manual', 'Manual'), ('rule', 'Rule'), ('inherited', 'Inherited'), ('split', 'Split')], default='', max_length=9),
        ),
        migrations.AddConstraint(
            model_name='ruleapplicationentry',
            constraint=models.CheckConstraint(condition=models.Q(('previous_category_source__in', ('', 'manual', 'rule', 'inherited', 'split'))), name='rule_application_prev_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('category_source__in', ('', 'manual', 'rule', 'inherited', 'split'))), name='transaction_category_source_valid'),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_splits', to='finance.category'),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='refundlink',
            name='original_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_links', to='finance.transactionsplit'),
        ),
        migrations.AddConstraint(
            model_name='transactionsplit',
            constraint=models.UniqueConstraint(fields=('transaction', 'position'), name='transaction_split_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='transactionsplit',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', 0), _negated=True), name='transaction_split_amount_nonzero'),
        ),
    ]
