# Generated by Django 5.2.17 on 2026-10-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_transaction_splits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=8)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('private', 'Private'), ('household', 'Household')], default='private', max_length=9)),
                ('rollover_enabled', models.BooleanField(default=False)),
                ('rollover_started_month', models.DateField(blank=True, null=True)),
                ('rollover_enabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.category')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.person')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField()),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='finance.budget')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRolloverReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_rollover_resets', to='finance.person')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollover_resets', to='finance.budget')),
            ],
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('household__isnull', True), ('scope', 'private')), models.Q(('household__isnull', False), ('scope', 'household')), _connector='OR'), name='budget_scope_matches_household'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rollover_enabled', False), ('rollover_started_month__isnull', True)), models.Q(('rollover_enabled', True), ('rollover_started_month__isnull', False)), _connector='OR'), name='budget_rollover_start_when_enabled'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='budget_archive_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False), ('scope', 'private'), ('status', 'active')), fields=('owner', 'category'), name='budget_one_active_private_category'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True), ('scope', 'private'), ('status', 'active')), fields=('owner',), name='budget_one_active_private_total'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False), ('scope', 'household'), ('status', 'active')), fields=('household', 'category'), name='budget_one_active_household_category'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True), ('scope', 'household'), ('status', 'active')), fields=('household',), name='budget_one_active_household_total'),
        ),
        migrations.AddConstraint(
            model_name='budgetamount',
            constraint=models.UniqueConstraint(fields=('budget', 'effective_month'), name='budget_amount_unique_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetamount',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='budget_amount_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='budgetamount',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='budget_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='budgetamount',
            constraint=models.CheckConstraint(condition=models.Q(('effective_month__day', 1)), name='budget_amount_month_start'),
        ),
        migrations.AddConstraint(
            model_name='budgetrolloverreset',
            constraint=models.UniqueConstraint(fields=('budget', 'month'), name='budget_rollover_reset_unique_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetrolloverreset',
            constraint=models.CheckConstraint(condition=models.Q(('month__day', 1)), name='budget_rollover_reset_month_start'),
        ),
    ]
