# Generated by Django 5.2.17 on 2026-10-03 14:31

import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCsvMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=8)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('headers', models.JSONField(validators=[finance.models.validate_stored_csv_headers])),
                ('date_column', models.CharField(max_length=255)),
                ('description_column', models.CharField(max_length=255)),
                ('date_format', models.CharField(max_length=16)),
                ('number_format', models.CharField(max_length=16)),
                ('amount_mode', models.CharField(max_length=8)),
                ('amount_column', models.CharField(blank=True, default='', max_length=255)),
                ('debit_column', models.CharField(blank=True, default='', max_length=255)),
                ('credit_column', models.CharField(blank=True, default='', max_length=255)),
                ('currency_column', models.CharField(blank=True, default='', max_length=255)),
                ('invert_sign', models.BooleanField(default=False)),
                ('description_mode', models.CharField(default='column', max_length=12)),
                ('payee_column', models.CharField(blank=True, default='', max_length=255)),
                ('memo_column', models.CharField(blank=True, default='', max_length=255)),
                ('source_id_column', models.CharField(blank=True, default='', max_length=255)),
                ('excluded_original_columns', models.JSONField(default=list, validators=[finance.models.validate_header_name_list])),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_csv_mappings', to='finance.person')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_csv_mappings', to='finance.household')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='default_saved_csv_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_accounts', to='finance.savedcsvmapping'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='saved_csv_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='finance.savedcsvmapping'),
        ),
        migrations.AddConstraint(
            model_name='savedcsvmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('household', 'name'), name='saved_csv_mapping_unique_active_name_per_household'),
        ),
        migrations.AddConstraint(
            model_name='savedcsvmapping',
            constraint=models.CheckConstraint(condition=models.Q(('amount_mode__in', ('signed', 'separate'))), name='saved_csv_mapping_amount_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='savedcsvmapping',
            constraint=models.CheckConstraint(condition=models.Q(('description_mode__in', ('column', 'payee_memo'))), name='saved_csv_mapping_description_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='savedcsvmapping',
            constraint=models.CheckConstraint(condition=models.Q(('date_format__in', ('mdy_slash_4', 'mdy_slash_2', 'dmy_slash_4', 'iso'))), name='saved_csv_mapping_date_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='savedcsvmapping',
            constraint=models.CheckConstraint(condition=models.Q(('number_format__in', ('dot_comma', 'comma_dot', 'dot_none', 'comma_none'))), name='saved_csv_mapping_number_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='savedcsvmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='saved_csv_mapping_archive_state_consistent'),
        ),
    ]
