# Generated by Django 5.2.17 on 2026-10-03 13:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='finance.household')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_links', to='finance.tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='finance.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_transactions', through='finance.TransactionTag', to='finance.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('household'), name='tag_unique_name_per_household'),
        ),
        migrations.AddConstraint(
            model_name='transactiontag',
            constraint=models.UniqueConstraint(fields=('transaction', 'tag'), name='transaction_tag_unique'),
        ),
    ]
