# Generated by Django 5.2.17 on 2026-10-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0021_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringseriesmember",
            name="source",
            field=models.CharField(
                choices=[("detected", "Detected"), ("manual", "Manual")],
                default="detected",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringseriesmember",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ("detected", "manual"))),
                name="recurring_member_source_valid",
            ),
        ),
        migrations.CreateModel(
            name="RecurringExclusion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_exclusions",
                        to="finance.person",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_exclusions",
                        to="finance.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="recurringexclusion",
            constraint=models.UniqueConstraint(
                fields=("person", "transaction"),
                name="recurring_exclusion_person_transaction",
            ),
        ),
    ]
