# Generated by Django 5.2.17 on 2026-10-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_budget'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='account_type_valid',
        ),
        migrations.AddField(
            model_name='account',
            name='secured_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='securing_loans', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit card'), ('investment', 'Investment'), ('real_estate', 'Real estate'), ('vehicle', 'Vehicle'), ('precious_metals', 'Precious metals'), ('other_asset', 'Other asset'), ('loan', 'Loan')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ('checking', 'savings', 'credit_card', 'investment', 'real_estate', 'vehicle', 'precious_metals', 'other_asset', 'loan'))), name='account_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('secured_asset__isnull', True), ('account_type', 'loan'), _connector='OR'), name='account_secured_asset_requires_loan'),
        ),
    ]
