# Generated by Django 5.2.17 on 2026-10-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_transaction_notes_and_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sync', 'Sync'), ('recurring_price', 'Recurring price change'), ('recurring_missed', 'Missed recurring charge'), ('budget', 'Budget'), ('large_transaction', 'Large transaction'), ('monthly_review', 'Monthly review')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='finance.account')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='finance.person')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='alert_recipient_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='alert_unique_recipient_dedupe'), models.CheckConstraint(condition=models.Q(('kind__in', ('sync', 'recurring_price', 'recurring_missed', 'budget', 'large_transaction', 'monthly_review'))), name='alert_kind_valid')],
            },
        ),
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_enabled', models.BooleanField(default=True)),
                ('recurring_price_enabled', models.BooleanField(default=True)),
                ('recurring_missed_enabled', models.BooleanField(default=True)),
                ('budget_enabled', models.BooleanField(default=True)),
                ('large_transaction_enabled', models.BooleanField(default=True)),
                ('monthly_review_enabled', models.BooleanField(default=True)),
                ('large_transaction_minor', models.BigIntegerField(blank=True, help_text='USD threshold in minor units. Empty means large-transaction alerts are off.', null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alert_settings', to='finance.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('large_transaction_minor__isnull', True), ('large_transaction_minor__gte', 0), _connector='OR'), name='alert_settings_large_threshold_non_negative')],
            },
        ),
    ]
