# Generated by Django 5.2.17 on 2026-10-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0024_recurring_grouping"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("harness_session_id", models.CharField(blank=True, default="", max_length=120)),
                ("backend", models.CharField(blank=True, default="", max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("used_account_ids", models.JSONField(default=list)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("tool_call_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="finance.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiConversationMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("error", "Error")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("backend", models.CharField(blank=True, default="", max_length=32)),
                ("figures", models.JSONField(default=list)),
                ("notices", models.JSONField(default=list)),
                ("page_context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="finance.aiconversation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="aiconversationmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(role__in=("user", "assistant", "error")),
                name="ai_conversation_message_role_valid",
            ),
        ),
    ]
