# Generated by Django 5.2.17 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0027_ai_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconversation",
            name="harness_connection",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
