# Generated by Django 5.2.17 on 2026-10-04 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_bulk_edit_undo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a 32-character hexadecimal stored name.', regex='^[0-9a-f]{32}$')])),
                ('content_type', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/webp', 'WebP'), ('image/heic', 'HEIC'), ('application/pdf', 'PDF')], max_length=16)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.transaction')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to='finance.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('content_type__in', ('image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/pdf'))), name='receipt_content_type_valid'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0), ('size_bytes__lte', 10485760)), name='receipt_size_within_cap')],
            },
        ),
    ]
