# Generated by Django 5.2.17 on 2026-10-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_shared_local_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetComparisonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_column', models.CharField(max_length=255)),
                ('income_column', models.CharField(max_length=255)),
                ('spending_column', models.CharField(max_length=255)),
                ('spending_sign', models.CharField(choices=[('unsigned', 'Unsigned (positive spending)'), ('signed', 'Signed (negative is spending)')], default='unsigned', max_length=16)),
                ('tolerance_minor', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_comparison_settings', to='finance.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('spending_sign__in', ('unsigned', 'signed'))), name='sheet_comparison_spending_sign_valid')],
            },
        ),
        migrations.CreateModel(
            name='SheetMonthTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('income_minor', models.BigIntegerField()),
                ('spending_minor', models.BigIntegerField()),
                ('source', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_month_totals', to='finance.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'month'), name='sheet_month_total_unique_member_month'), models.CheckConstraint(condition=models.Q(('month__day', 1)), name='sheet_month_total_month_start')],
            },
        ),
    ]
