# Generated by Django 5.2.17 on 2026-10-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0043_bills_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='require_passkey_after_password',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to='finance.person')),
            ],
            options={
                'indexes': [models.Index(fields=['member', '-created_at'], name='passkey_member_created_idx')],
            },
        ),
    ]
