# Generated by Django 5.2.17 on 2026-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0044_passkeys'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='import_source_valid',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('huntington', 'Huntington Bank'), ('capital_one', 'Capital One'), ('apple_card', 'Apple Card'), ('vanguard', 'Vanguard'), ('simplefin', 'SimpleFIN'), ('ofx', 'OFX / QFX')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('huntington', 'capital_one', 'apple_card', 'vanguard', 'simplefin', 'ofx'))), name='import_source_valid'),
        ),
    ]
