# Generated by Django 5.2.17 on 2026-10-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0044_passkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="email_notice_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertsettings',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertsettings',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
