# Generated by Django 5.2.17 on 2026-10-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0046_ofx_import_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationmessage',
            name='claim_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiconversationmessage',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconversationmessage',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconversationmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.aiconversationmessage'),
        ),
        migrations.AddField(
            model_name='aiconversationmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='done', max_length=8),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['status', 'claimed_at'], name='ai_chat_turn_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiconversationmessage',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'done', 'failed'))), name='ai_conversation_message_status_valid'),
        ),
    ]
