# Generated by Django 5.2.17 on 2026-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0047_chat_background_turns'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='import_source_valid',
        ),
        migrations.RemoveConstraint(
            model_name='transactioncorrectionhistory',
            name='correction_history_value_shape',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('huntington', 'Huntington Bank'), ('capital_one', 'Capital One'), ('apple_card', 'Apple Card'), ('vanguard', 'Vanguard'), ('simplefin', 'SimpleFIN'), ('ofx', 'OFX / QFX'), ('manual', 'Manual')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transactioncorrectionhistory',
            name='field_name',
            field=models.CharField(choices=[('transaction_date', 'Date'), ('description', 'Description'), ('amount_minor', 'Amount'), ('category', 'Category'), ('exclusion', 'Transfer exclusion'), ('refund_link', 'Refund link'), ('note', 'Note'), ('tags', 'Tags'), ('deleted', 'Deleted')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('huntington', 'capital_one', 'apple_card', 'vanguard', 'simplefin', 'ofx', 'manual'))), name='import_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='transactioncorrectionhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('field_name', 'transaction_date'), ('new_amount_minor__isnull', True), ('new_date__isnull', False), ('new_description', ''), ('previous_amount_minor__isnull', True), ('previous_date__isnull', False), ('previous_description', '')), models.Q(('currency', ''), ('field_name__in', ('description', 'category', 'exclusion', 'refund_link', 'note', 'tags', 'deleted')), ('new_amount_minor__isnull', True), ('new_date__isnull', True), ('previous_amount_minor__isnull', True), ('previous_date__isnull', True)), models.Q(('currency', 'USD'), ('field_name', 'amount_minor'), ('new_amount_minor__isnull', False), ('new_date__isnull', True), ('new_description', ''), ('previous_amount_minor__isnull', False), ('previous_date__isnull', True), ('previous_description', '')), _connector='OR'), name='correction_history_value_shape'),
        ),
    ]
