# Generated by Django 5.2.17 on 2026-10-06 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_manual_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('set_category', 'Set category'), ('create_rule', 'Create rule'), ('set_budget', 'Set budget'), ('add_tags', 'Add tags')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('stale', 'No longer applies')], default='pending', max_length=10)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='finance.aiconversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='finance.aiconversationmessage')),
            ],
            options={
                'ordering': ('pk',),
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ('set_category', 'create_rule', 'set_budget', 'add_tags'))), name='ai_proposal_kind_valid'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'applied', 'dismissed', 'stale'))), name='ai_proposal_status_valid')],
            },
        ),
    ]
