# Generated by Django 5.2.17 on 2026-10-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0049_ai_proposal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiproviderconnection',
            name='ai_connection_kind_valid',
        ),
        migrations.AddField(
            model_name='aiproviderconnection',
            name='use_for_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiproviderconnection',
            name='use_for_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aiproviderconnection',
            name='base_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiproviderconnection',
            name='kind',
            field=models.CharField(choices=[('agent_harness', 'Agent Harness'), ('anthropic_api', 'Anthropic API'), ('openai_api', 'OpenAI API')], default='agent_harness', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('agent_harness', 'anthropic_api', 'openai_api'))), name='ai_connection_kind_valid'),
        ),
    ]
