# Generated by Django 5.2.17 on 2026-10-06 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0051_offer_local_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconnection',
            name='offer_plan_links',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AiPlanLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(max_length=16)),
                ('needs_login', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='finance.aiproviderconnection')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan_links', to='finance.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'backend'), name='ai_plan_link_unique_person_backend'), models.CheckConstraint(condition=models.Q(('backend__in', ('claude', 'codex'))), name='ai_plan_link_backend_valid')],
            },
        ),
    ]
