# Generated by Django 5.2.17 on 2026-10-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0053_recurring_detection_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['amount_minor', 'transaction_date'], name='txn_transfer_candidate_idx'),
        ),
    ]
