# Generated by Django 5.2.17 on 2026-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0054_transfer_candidate_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='ai_job_due_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['status', 'updated_at'], name='ai_job_stale_idx'),
        ),
    ]
