# Generated by Django 5.2.17 on 2026-10-08 13:01

import django.db.models.deletion
import django.utils.timezone
import finance.audit_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0055_ai_job_poll_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action', models.CharField(choices=[('account_shared', 'Account shared'), ('account_unshared', 'Account unshared'), ('share_mode_changed', 'Sharing mode changed'), ('account_archived', 'Account archived'), ('account_deleted', 'Account deleted')], max_length=24)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('started', 'Started'), ('failed', 'Failed')], default='succeeded', max_length=12)),
                ('actor_kind', models.CharField(choices=[('member', 'Member'), ('scheduler', 'Scheduler'), ('operator', 'Operator')], max_length=12)),
                ('target_type', models.CharField(choices=[('account', 'Account')], default='account', max_length=12)),
                ('target_id', models.PositiveBigIntegerField()),
                ('source', models.CharField(choices=[('ui', 'UI'), ('job', 'Job'), ('cli', 'CLI'), ('chat_confirmation', 'Chat confirmation')], max_length=20)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('changed_fields', models.JSONField(blank=True, default=list, validators=[finance.audit_models.validate_changed_fields])),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='finance.account')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to='finance.person')),
                ('effective_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effective_audit_actions', to='finance.person')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='finance.household')),
                ('private_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_audit_events', to='finance.person')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['occurred_at', 'id'], name='audit_time_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_id__gt', 0)), name='audit_positive_target'), models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('household__isnull', True), ('private_owner__isnull', True)), models.Q(('household__isnull', True), ('private_owner__isnull', False)), models.Q(('household__isnull', False), ('private_owner__isnull', True)), _connector='OR'), name='audit_target_or_deletion_audience')],
            },
        ),
    ]
