# Generated by Django 5.2.17 on 2026-10-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0056_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='affected_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_audit_events', to='finance.person'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('account_shared', 'Account shared'), ('account_unshared', 'Account unshared'), ('share_mode_changed', 'Sharing mode changed'), ('account_archived', 'Account archived'), ('account_deleted', 'Account deleted'), ('account_created', 'Account created'), ('account_renamed', 'Account renamed'), ('account_owner_changed', 'Account ownership changed'), ('debt_terms_changed', 'Debt terms changed'), ('loan_pairing_changed', 'Loan pairing changed'), ('household_created', 'Household created'), ('invitation_created', 'Invitation created'), ('invitation_accepted', 'Invitation accepted'), ('member_left', 'Member left household'), ('google_connected', 'Google sign-in connected'), ('google_disconnected', 'Google sign-in disconnected'), ('password_added', 'Password added'), ('password_changed', 'Password changed'), ('password_removed', 'Password removed'), ('passkey_requirement_changed', 'Passkey requirement changed'), ('session_revoked', 'Session revoked'), ('other_sessions_revoked', 'Other sessions revoked'), ('privacy_accepted', 'Privacy policy accepted'), ('privacy_declined', 'Privacy policy declined'), ('simplefin_connected', 'SimpleFIN connected'), ('simplefin_disconnected', 'SimpleFIN disconnected'), ('simplefin_links_changed', 'SimpleFIN account links changed'), ('ai_harness_connected', 'AI harness connected'), ('ai_harness_disconnected', 'AI harness disconnected'), ('ai_key_connected', 'AI key connected'), ('ai_key_replaced', 'AI key replaced'), ('ai_key_disconnected', 'AI key disconnected'), ('ai_defaults_changed', 'AI defaults changed'), ('ai_local_offer_changed', 'Local-model offer changed'), ('ai_shared_local_changed', 'Shared local-model choice changed'), ('plan_link_offer_changed', 'Plan-link offer changed'), ('notification_preferences_changed', 'Notification preferences changed'), ('notification_address_changed', 'Notification address changed'), ('bills_calendar_changed', 'Bill calendar settings changed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='target_type',
            field=models.CharField(choices=[('account', 'Account'), ('member', 'Member'), ('household', 'Household'), ('invitation', 'Invitation'), ('session', 'Session'), ('connection', 'Connection'), ('setting', 'Setting')], default='account', max_length=16),
        ),
    ]
