# Generated by Django 5.2.17 on 2026-10-08 15:34

import finance.audit_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0056_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, validators=[finance.audit_models.validate_metadata]),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('account_shared', 'Account shared'), ('account_unshared', 'Account unshared'), ('share_mode_changed', 'Sharing mode changed'), ('account_archived', 'Account archived'), ('account_deleted', 'Account deleted'), ('record_created', 'Created'), ('record_edited', 'Edited'), ('record_deleted', 'Deleted'), ('record_archived', 'Archived'), ('record_restored', 'Restored'), ('record_enabled', 'Enabled'), ('record_disabled', 'Disabled'), ('record_completed', 'Completed'), ('default_changed', 'Default changed'), ('rollover_toggled', 'Rollover toggled'), ('tags_changed', 'Tags changed'), ('import_committed', 'Import committed'), ('import_no_new_rows', 'Import completed, no new rows'), ('import_undone', 'Import undone'), ('transaction_corrected', 'Transaction corrected'), ('bulk_applied', 'Bulk edit applied'), ('bulk_undone', 'Bulk edit undone'), ('rule_applied', 'Rule applied'), ('rule_reversed', 'Rule application reversed'), ('recurring_confirmed', 'Recurring confirmed'), ('recurring_dismissed', 'Recurring dismissed'), ('recurring_merged', 'Recurring merged'), ('recurring_added', 'Recurring charge added'), ('recurring_removed', 'Recurring charge removed'), ('recurring_canceled', 'Recurring canceled'), ('recurring_resumed', 'Recurring resumed'), ('recurring_price_ack', 'Recurring price change acknowledged'), ('receipt_attached', 'Receipt attached'), ('receipt_removed', 'Receipt removed'), ('download_prepared', 'Download response prepared')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='source',
            field=models.CharField(choices=[('ui', 'UI'), ('job', 'Job'), ('cli', 'CLI'), ('chat_confirmation', 'Chat confirmation'), ('bulk', 'Bulk edit'), ('rule', 'Automatic rule')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='target_type',
            field=models.CharField(choices=[('account', 'Account'), ('import_batch', 'Import batch'), ('transaction', 'Transaction'), ('balance', 'Balance or valuation'), ('budget', 'Budget'), ('planned_item', 'Planned item'), ('goal', 'Savings goal'), ('category', 'Category'), ('tag', 'Tag'), ('csv_mapping', 'Saved CSV mapping'), ('rule', 'Category rule'), ('recurring', 'Recurring series'), ('receipt', 'Receipt'), ('export', 'Data download'), ('bulk_edit', 'Bulk edit')], default='account', max_length=16),
        ),
    ]
