# Generated by Django 5.2.17 on 2026-10-08 17:35

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0058_audit_workflow_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='target_type',
            field=models.CharField(choices=[('account', 'Account'), ('member', 'Member'), ('household', 'Household'), ('invitation', 'Invitation'), ('session', 'Session'), ('connection', 'Connection'), ('setting', 'Setting'), ('import_batch', 'Import batch'), ('transaction', 'Transaction'), ('balance', 'Balance or valuation'), ('budget', 'Budget'), ('planned_item', 'Planned item'), ('goal', 'Savings goal'), ('category', 'Category'), ('tag', 'Tag'), ('csv_mapping', 'Saved CSV mapping'), ('rule', 'Category rule'), ('recurring', 'Recurring series'), ('receipt', 'Receipt'), ('export', 'Data download'), ('bulk_edit', 'Bulk edit'), ('ai_job', 'AI job'), ('chat_turn', 'Chat turn'), ('review', 'Monthly review'), ('alert', 'Alert')], default='account', max_length=16),
        ),

        migrations.AddField(model_name="aijob", name="audit_run_id", field=models.UUIDField(default=uuid.uuid4, editable=False)),
        migrations.AddField(
            model_name='auditevent',
            name='declared_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_operator_events', to='finance.person'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('operation_outcome', 'Operation outcome'), ('account_shared', 'Account shared'), ('account_unshared', 'Account unshared'), ('share_mode_changed', 'Sharing mode changed'), ('account_archived', 'Account archived'), ('account_deleted', 'Account deleted'), ('account_created', 'Account created'), ('account_renamed', 'Account renamed'), ('account_owner_changed', 'Account ownership changed'), ('debt_terms_changed', 'Debt terms changed'), ('loan_pairing_changed', 'Loan pairing changed'), ('household_created', 'Household created'), ('invitation_created', 'Invitation created'), ('invitation_accepted', 'Invitation accepted'), ('member_left', 'Member left household'), ('google_connected', 'Google sign-in connected'), ('google_disconnected', 'Google sign-in disconnected'), ('password_added', 'Password added'), ('password_changed', 'Password changed'), ('password_removed', 'Password removed'), ('passkey_requirement_changed', 'Passkey requirement changed'), ('session_revoked', 'Session revoked'), ('other_sessions_revoked', 'Other sessions revoked'), ('privacy_accepted', 'Privacy policy accepted'), ('privacy_declined', 'Privacy policy declined'), ('simplefin_connected', 'SimpleFIN connected'), ('simplefin_disconnected', 'SimpleFIN disconnected'), ('simplefin_links_changed', 'SimpleFIN account links changed'), ('ai_harness_connected', 'AI harness connected'), ('ai_harness_disconnected', 'AI harness disconnected'), ('ai_key_connected', 'AI key connected'), ('ai_key_replaced', 'AI key replaced'), ('ai_key_disconnected', 'AI key disconnected'), ('ai_defaults_changed', 'AI defaults changed'), ('ai_local_offer_changed', 'Local-model offer changed'), ('ai_shared_local_changed', 'Shared local-model choice changed'), ('plan_link_offer_changed', 'Plan-link offer changed'), ('notification_preferences_changed', 'Notification preferences changed'), ('notification_address_changed', 'Notification address changed'), ('bills_calendar_changed', 'Bill calendar settings changed'), ('record_created', 'Created'), ('record_edited', 'Edited'), ('record_deleted', 'Deleted'), ('record_archived', 'Archived'), ('record_restored', 'Restored'), ('record_enabled', 'Enabled'), ('record_disabled', 'Disabled'), ('record_completed', 'Completed'), ('default_changed', 'Default changed'), ('rollover_toggled', 'Rollover toggled'), ('tags_changed', 'Tags changed'), ('import_committed', 'Import committed'), ('import_no_new_rows', 'Import completed, no new rows'), ('import_undone', 'Import undone'), ('transaction_corrected', 'Transaction corrected'), ('bulk_applied', 'Bulk edit applied'), ('bulk_undone', 'Bulk edit undone'), ('rule_applied', 'Rule applied'), ('rule_reversed', 'Rule application reversed'), ('recurring_confirmed', 'Recurring confirmed'), ('recurring_dismissed', 'Recurring dismissed'), ('recurring_merged', 'Recurring merged'), ('recurring_added', 'Recurring charge added'), ('recurring_removed', 'Recurring charge removed'), ('recurring_canceled', 'Recurring canceled'), ('recurring_resumed', 'Recurring resumed'), ('recurring_price_ack', 'Recurring price change acknowledged'), ('receipt_attached', 'Receipt attached'), ('receipt_removed', 'Receipt removed'), ('download_prepared', 'Download response prepared')], max_length=40),
        ),
    ]
