# Generated by Django 5.2.17 on 2026-10-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0060_reevaluate_auto_marked_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='savings_buffer_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='finance.savingsgoal'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='time_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.CheckConstraint(condition=models.Q(('savings_buffer_minor__isnull', True), ('savings_buffer_minor__gte', 0), _connector='OR'), name='household_savings_buffer_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('priority__isnull', True), ('priority__gte', 1), _connector='OR'), name='savings_goal_priority_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('depends_on__isnull', True), models.Q(('depends_on', models.F('pk')), _negated=True), _connector='OR'), name='savings_goal_not_self_dependent'),
        ),
    ]
