# Generated by Django 5.2.17 on 2026-10-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0062_bound_budget_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationmessage',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
