from django.urls import path
from django.views.generic import RedirectView

from finance import (
    account_views,
    ai_views,
    budget_views,
    category_suggestion_views,
    net_worth_views,
    planning_views,
    rule_views,
    savings_goal_views,
    simplefin_views,
    views,
)
from finance.csv_import import views as csv_import_views


urlpatterns = [
    path("health/", views.health, name="health"),
    path("", views.home, name="home"),
    path("spending/", views.spending_by_category, name="spending-by-category"),
    path(
        "spending/category/uncategorized/",
        views.spending_category_detail,
        name="spending-category-uncategorized",
    ),
    path(
        "spending/category/<int:category_id>/",
        views.spending_category_detail,
        name="spending-category-detail",
    ),
    path("net-worth/", net_worth_views.net_worth, name="net-worth"),
    path("privacy-policy/", views.privacy_policy, name="privacy-policy"),
    path("privacy-policy/<int:version>/", views.privacy_policy, name="privacy-policy-version"),
    path("privacy-policy/respond/", views.privacy_policy_respond, name="privacy-policy-respond"),
    path("sign-in/", views.sign_in, name="login"),
    path("sign-in/google/", views.start_google_sign_in, name="google-sign-in"),
    path("accounts/google/login/", views.google_oauth_login, name="google_login"),
    path("accounts/google/login/callback/", views.google_oauth_callback, name="google_callback"),
    path("sign-out/", views.sign_out, name="logout"),
    path("setup/", views.setup, name="setup"),
    path("settings/", RedirectView.as_view(pattern_name="account-settings", query_string=True)),
    path("settings/security/", views.account_settings, name="account-settings"),
    path("settings/connections/", simplefin_views.connections, name="simplefin-connections"),
    path("settings/connections/sync/", simplefin_views.connections_sync, name="simplefin-sync"),
    path(
        "settings/connections/disconnect/",
        simplefin_views.connections_disconnect,
        name="simplefin-disconnect",
    ),
    path("settings/household/", views.invite, name="invite"),
    path("settings/household/leave/", views.leave_household_view, name="leave-household"),
    path("settings/categories/", views.category_list, name="category-list"),
    path("settings/categories/rules/", rule_views.category_rule_list, name="category-rule-list"),
    path(
        "settings/categories/rules/<int:rule_id>/",
        rule_views.category_rule_detail,
        name="category-rule-detail",
    ),
    path(
        "settings/categories/rules/applications/<int:application_id>/reverse/",
        rule_views.category_rule_application_reverse,
        name="category-rule-application-reverse",
    ),
    path("settings/tags/", views.tag_list, name="tag-list"),
    path("settings/data/", views.settings_data, name="settings-data"),
    path("settings/data/export/", views.account_export, name="account-export"),
    path("settings/ai/", views.settings_ai, name="settings-ai"),
    path("settings/ai/connect/", ai_views.ai_connect, name="ai-connect"),
    path("settings/ai/disconnect/", ai_views.ai_disconnect, name="ai-disconnect"),
    path("settings/ai/defaults/", ai_views.ai_save_defaults, name="ai-defaults"),
    path("account/", RedirectView.as_view(pattern_name="account-settings", permanent=True, query_string=True)),
    path("account/ai/connect/", RedirectView.as_view(pattern_name="ai-connect", permanent=True, query_string=True)),
    path(
        "account/ai/disconnect/",
        RedirectView.as_view(pattern_name="ai-disconnect", permanent=True, query_string=True),
    ),
    path("account/ai/defaults/", RedirectView.as_view(pattern_name="ai-defaults", permanent=True, query_string=True)),
    path("account/export/", RedirectView.as_view(pattern_name="account-export", permanent=True, query_string=True)),
    path("reauth/", views.reauth, name="reauth"),
    path("reauth/google/", views.start_google_reauth, name="reauth-google"),
    path("invite/", RedirectView.as_view(pattern_name="invite", permanent=True, query_string=True)),
    path("household/leave/", RedirectView.as_view(pattern_name="leave-household", permanent=True, query_string=True)),
    path("join/", views.join, name="join"),
    path("recover/", views.recover, name="recover"),
    path("accounts/", account_views.account_list, name="account-list"),
    path(
        "accounts/connections/",
        RedirectView.as_view(pattern_name="simplefin-connections", permanent=True, query_string=True),
    ),
    path(
        "accounts/connections/sync/",
        RedirectView.as_view(pattern_name="simplefin-sync", permanent=True, query_string=True),
    ),
    path(
        "accounts/connections/disconnect/",
        RedirectView.as_view(pattern_name="simplefin-disconnect", permanent=True, query_string=True),
    ),
    path("accounts/<int:account_id>/rename/", account_views.account_rename, name="account-rename"),
    path("accounts/<int:account_id>/share/", account_views.account_share, name="account-share"),
    path("accounts/<int:account_id>/share-mode/", account_views.account_change_share_mode, name="account-share-mode"),
    path("accounts/<int:account_id>/unshare/", account_views.account_unshare, name="account-unshare"),
    path("accounts/<int:account_id>/archive/", account_views.account_archive, name="account-archive"),
    path("accounts/<int:account_id>/delete/", account_views.account_delete, name="account-delete"),
    path("accounts/<int:account_id>/balances/", net_worth_views.account_balances, name="account-balances"),
    path("accounts/<int:account_id>/pair/", net_worth_views.account_pair_loan, name="account-pair-loan"),
    path(
        "accounts/<int:account_id>/balances/<int:snapshot_id>/edit/",
        net_worth_views.account_snapshot_edit,
        name="account-snapshot-edit",
    ),
    path(
        "accounts/<int:account_id>/balances/<int:snapshot_id>/delete/",
        net_worth_views.account_snapshot_delete,
        name="account-snapshot-delete",
    ),
    path("accounts/<int:account_id>/imports/preview/", csv_import_views.csv_preview, name="csv-import-preview"),
    path("accounts/<int:account_id>/imports/<int:batch_id>/undo/", csv_import_views.csv_undo_import, name="csv-import-undo"),
    path("transactions/", views.transaction_list, name="transaction-list"),
    path("transactions/suggest-categories/", category_suggestion_views.suggest_categories, name="suggest-categories"),
    path(
        "transactions/suggestions/accept-all/",
        category_suggestion_views.suggestion_accept_all,
        name="suggestion-accept-all",
    ),
    path(
        "transactions/suggestions/<int:suggestion_id>/accept/",
        category_suggestion_views.suggestion_accept,
        name="suggestion-accept",
    ),
    path(
        "transactions/suggestions/<int:suggestion_id>/reject/",
        category_suggestion_views.suggestion_reject,
        name="suggestion-reject",
    ),
    path("transactions/<int:transaction_id>/edit/", views.transaction_edit, name="transaction-edit"),
    path("transactions/<int:transaction_id>/note-tags/", views.transaction_note_tags, name="transaction-note-tags"),
    path("transactions/<int:transaction_id>/category/", views.transaction_categorize, name="transaction-categorize"),
    path("transactions/<int:transaction_id>/split/", views.transaction_split, name="transaction-split"),
    path("transactions/<int:transaction_id>/unsplit/", views.transaction_unsplit, name="transaction-unsplit"),
    path(
        "transactions/<int:transaction_id>/splits/<int:part_id>/category/",
        views.transaction_split_part_category,
        name="transaction-split-part-category",
    ),
    path("transactions/<int:transaction_id>/refund/", views.transaction_link_refund, name="transaction-link-refund"),
    path("categories/", RedirectView.as_view(pattern_name="category-list", permanent=True, query_string=True)),
    path(
        "categories/rules/",
        RedirectView.as_view(pattern_name="category-rule-list", permanent=True, query_string=True),
    ),
    path(
        "categories/rules/<int:rule_id>/",
        RedirectView.as_view(pattern_name="category-rule-detail", permanent=True, query_string=True),
    ),
    path("tags/", RedirectView.as_view(pattern_name="tag-list", permanent=True, query_string=True)),
    path(
        "categories/rules/applications/<int:application_id>/reverse/",
        RedirectView.as_view(pattern_name="category-rule-application-reverse", permanent=True, query_string=True),
    ),
    path("transfers/", views.transfer_review, name="transfer-review"),
    path("recurring/", views.recurring_review, name="recurring-review"),
    path("planning/items/", planning_views.planned_item_list, name="planned-items"),
    path("planning/items/<int:item_id>/edit/", planning_views.planned_item_edit, name="planned-item-edit"),
    path("planning/items/<int:item_id>/disable/", planning_views.planned_item_disable, name="planned-item-disable"),
    path("planning/items/<int:item_id>/enable/", planning_views.planned_item_enable, name="planned-item-enable"),
    path("planning/budgets/", budget_views.budget_list, name="budgets"),
    path("planning/budgets/<int:budget_id>/edit/", budget_views.budget_edit, name="budget-edit"),
    path("planning/budgets/<int:budget_id>/archive/", budget_views.budget_archive, name="budget-archive"),
    path(
        "planning/budgets/<int:budget_id>/rollover/",
        budget_views.budget_rollover_toggle,
        name="budget-rollover-toggle",
    ),
    path(
        "planning/budgets/<int:budget_id>/rollover/reset/",
        budget_views.budget_rollover_reset,
        name="budget-rollover-reset",
    ),
    path("planning/goals/", savings_goal_views.savings_goal_list, name="savings-goals"),
    path("planning/goals/<int:goal_id>/edit/", savings_goal_views.savings_goal_edit, name="savings-goal-edit"),
    path("planning/goals/<int:goal_id>/complete/", savings_goal_views.savings_goal_complete, name="savings-goal-complete"),
    path("planning/goals/<int:goal_id>/reopen/", savings_goal_views.savings_goal_reopen, name="savings-goal-reopen"),
    path("planning/goals/<int:goal_id>/archive/", savings_goal_views.savings_goal_archive, name="savings-goal-archive"),
    path(
        "planning/goals/<int:goal_id>/unarchive/",
        savings_goal_views.savings_goal_unarchive,
        name="savings-goal-unarchive",
    ),
]
