"""Shared bounds for member input and synchronous work."""
from datetime import date

MAX_DESCRIPTION_CHARS = 500
MAX_CHAT_PROMPT_CHARS = 8_000
MAX_PAGE_CONTEXT_CHARS = 2_000
MAX_CHAT_MESSAGES = 40
MAX_PROMPT_CHARS = 32_000
MAX_PROMPT_LINE_CHARS = 600
MAX_COLUMNS = 64
BUDGET_MONTH_FLOOR = date(2000, 1, 1)
BUDGET_FUTURE_MONTHS = 24
MAX_CARRY_MONTHS = 24
MAX_TRANSFER_CANDIDATES = 2_000
MAX_UNUSUAL_FLAGS = 50
MAX_UNUSUAL_ALERTS = 10
MAX_AI_FACTS_CHARS = 32_000
MAX_LARGE_ALERTS = 20
