"""OFX 1.6 scalar names whose SGML end tags may be omitted.

Derived from the ELEMENT declarations marked `- o` in the official OFX 1.6
DTD. This includes the older 1.x banking/card message sets. No DTD is loaded
at runtime and uploaded declarations are always rejected.
Source: https://financialdataexchange.org/wp-content/uploads/2025/12/OFX1.6.zip
"""

LEAF_TAGS = frozenset(
    """
    ACCRDINT ACCTBAL ACCTEDITMASK ACCTFORMAT ACCTID ACCTKEY ACCTREQUIRED ACCTTYPE ACCTTYPE2 ACTIVITY
    ADDR1 ADDR2 ADDR3 ADJAMT ADJDATE ADJDESC ADJNO AMTDUE APPID APPVER ASSETCLASS AUCTION AVAILACCTS
    AVAILCASH AVGCOSTBASIS BALAMT BALCLOSE BALDNLD BALMIN BALOPEN BALTYPE BANKBRANCH BANKCITY BANKID
    BANKNAME BANKPOSTALCODE BILLDETAILTABLETYPE BILLERID BILLERINFOURL BILLERNAME BILLID
    BILLPMTSTATUSCODE BILLPUB BILLREFINFO BILLSTATUSCODE BILLTYPE BOOKINGTEXT BRANCHID BRAND BROKERID
    BUSNAMEACCTHELD BUYPOWER BUYTYPE C CALLPRICE CALLTYPE CANADDPAYEE CANBILLPAY CANCELWND CANEMAIL
    CANMODMDLS CANMODPMTS CANMODXFERS CANMOTO CANMULTI CANNOTIFY CANPENDING CANRECUR CANSCHED
    CANSUPPORTGROUPID CANSUPPORTIMAGES CANSUPPORTUSERID CANUPDATEPRESNAMEADDRESS CANUSEDESC CANUSERANGE
    CASESEN CHARTYPE CHE.PTTACCTID CHECKING CHECKNUM CHGPINFIRST CHGUSERINFO CHKANDDEB CHKERROR
    CHKNUMEND CHKNUMSTART CHKSTATUS CITY CLIENTACTREQ CLIENTROUTING CLOSINGAVAIL CLTCOOKIE CODE COLNAME
    COLTYPE COMMISSION CONFMSG CONSUPOSTALCODE CORRECTACTION CORRECTFITID COUNT COUNTRY COUPONFREQ
    COUPONRT CREDITLIMIT CSPHONE CURDEF CURRATE CURSYM DATEBIRTH DAYPHONE DAYSTOPAY DAYSWITH DEBADJ
    DEBTCLASS DEBTTYPE DENOMINATOR DEPANDCREDIT DESC DETAILAVAILABLE DFLTDAYSTOPAY DIFFFIRSTPMT
    DIFFLASTPMT DOMXFERFEE DSCAMT DSCDATE DSCDESC DSCRATE DTACCTUP DTASOF DTAUCTION DTAVAIL DTBILL
    DTCALL DTCHANGED DTCLIENT DTCLOSE DTCOUPON DTCREATED DTDUE DTDUEBY DTEFF DTEND DTEXPIRE DTINFOCHG
    DTMAT DTNEXT DTOPEN DTPLACED DTPMTDUE DTPMTPRC DTPOSTED DTPOSTEND DTPOSTSTART DTPRICEASOF DTPROFUP
    DTPURCHASE DTSEEN DTSERVER DTSETTLE DTSTART DTTRADE DTUPDATE DTUSER DTXFERPRC DTXFERPRJ DTYIELDASOF
    DURATION EMAIL EVEPHONE EXTDPMTCHK EXTDPMTCHK2 EXTDPMTDSC2 EXTDPMTFOR FAXPHONE FEE FEEMSG FEES
    FIASSETCLASS FICERTID FID FIID FINALAMT FINAME FINCHG FIRSTNAME FITID FRACCASH FREQ FROM GAIN
    GENUSERKEY GETMIMESUP GROUPID HASEXTDPMT HASRECEXTDPMT HELDINACCT HELPMESSAGE IDSCOPE IMAGEURL
    INCBAL INCIMAGES INCLUDE INCLUDEBILLPMTSTATUS INCLUDEBILLSTATUS INCLUDECOUNTS INCLUDEDETAIL
    INCLUDESTATUSHIST INCLUDESUMMARY INCOMETYPE INCOO INITIALAMT INTLXFERFEE INVACCTTYPE INVALIDACCTTYPE
    INVALIDACCTTYPE2 INVDATE INVDESC INVNO INVPAIDAMT INVTOTALAMT ITA.CAUSALE LANGUAGE LASTNAME
    LIMITPRICE LITMAMT LITMCODE LITMDESC LOAD LOGO LOSTSYNC MAILSUP MARGINBALANCE MARKDOWN MARKUP MAX
    MEMO MEMO2 MESSAGE MESSAGE2 MFTYPE MIDDLENAME MIN MINAMTDUE MINPMTDUE MINUNITS MKTGINFO MKTVAL
    MODELWND MODPENDING N NAME NAMEACCTHELD NEEDTANPAYEE NEEDTANPMT NEEDTANTRANSFER NEWUNITS NEWUSERPASS
    NINSTS NONCE NOTIFYDESIRED NOTIFYWILLING NUMERATOR OFXSEC OLDUNITS ONETIMEPASS OODNLD OPTACTION
    OPTBUYTYPE OPTIONLEVEL OPTSELLTYPE OPTTYPE ORG PARVALUE PAYACCT PAYANDCREDIT PAYEEID PAYEEID2
    PAYEELSTID PAYEELSTID2 PAYEEMODPENDING PAYINSTRUCT PERCENT PHONE PINCH PMTBYADDR PMTBYPAYEEID
    PMTBYXFER PMTFOR PMTINSTRUMENTTYPE PMTPRCCODE PMTTYPE POSDNLD POSTALCODE POSTPROCWND POSTYPE PREAUTH
    PREAUTHTOKEN PREFETCHURL PREVBAL PROCDAYSOFF PROCENDTM PURANDADV PWTYPE RATING REASON RECSRVRTID
    RECSRVRTID2 REFNUM REFRESH REFRESHSUPT REINVCG REINVDIV REJECTIFMISSING RELFITID RELTYPE RESPFILEER
    RESTRICT RESTRICTION REVERSALFEES REVERSALFITID SECLISTRQDNLD SECNAME SECURED SECURITYNAME SELLALL
    SELLREASON SELLTYPE SESSCOOKIE SEVERITY SHORTBALANCE SHPERCTRCT SIC SIGNONREALM SPACES SPECIAL
    SPNAME SRVRTID SRVRTID2 STATE STATUSMODBY STOCKTYPE STOPPRICE STPCHKFEE STRIKEPRICE STSVIAMODS
    SUBACCT SUBACCTFROM SUBACCTFUND SUBACCTSEC SUBACCTTO SUBJECT SUPPORTDTAVAIL SUPTXDL SVC SVC2
    SVCSTATUS SVCSTATUS2 SWITCHALL SYNCERROR SYNCMODE TABLENAME TAN TAXES TAXEXEMPT TAXID TEMPPASS
    TFERACTION TICKER TO TOKEN TOKEN2 TOKENONLY TOTAL TOTALFEES TOTALINT TRANDNLD TRANSPSEC TRNAMT
    TRNTYPE TRNUID TSKEYEXPIRE TSPHONE TYPEDESC UNIQUEID UNIQUEIDTYPE UNITPRICE UNITS UNITSSTREET
    UNITSUSER UNITTYPE URL URL2 URLGETREDIRECT USEHTML USERID USERKEY USERPASS USPRODUCTTYPE VALIDATE
    VALUE VER WITHHOLDING XFERDAYSWITH XFERDEST XFERDFLTDAYSTOPAY XFERPRCCODE XFERSRC YIELD YIELDTOCALL
    YIELDTOMAT
    """.split()
)
