"""OFX 1.6 scalar names whose SGML end tags may be omitted.

Derived from the ELEMENT declarations marked `- o` in the official OFX 1.6
DTD. This includes the older 1.x banking/card message sets. No DTD is loaded
at runtime and uploaded declarations are always rejected.
Source: https://financialdataexchange.org/wp-content/uploads/2025/12/OFX1.6.zip
"""

LEAF_TAGS = frozenset(
    """
    ACCTBAL ACCTEDITMASK ACCTFORMAT ACCTID ACCTKEY ACCTREQUIRED ACCTTYPE ACCTTYPE2 ACTIVITY ADDR1 ADDR2
    ADDR3 ADJAMT ADJDATE ADJDESC ADJNO AMTDUE APPID APPVER AVAILACCTS BALAMT BALCLOSE BALMIN BALOPEN
    BALTYPE BANKBRANCH BANKCITY BANKID BANKNAME BANKPOSTALCODE BILLDETAILTABLETYPE BILLERID
    BILLERINFOURL BILLERNAME BILLID BILLPMTSTATUSCODE BILLPUB BILLREFINFO BILLSTATUSCODE BILLTYPE
    BOOKINGTEXT BRANCHID BRAND BUSNAMEACCTHELD C CANADDPAYEE CANBILLPAY CANCELWND CANEMAIL CANMODMDLS
    CANMODPMTS CANMODXFERS CANMOTO CANMULTI CANNOTIFY CANPENDING CANRECUR CANSCHED CANSUPPORTGROUPID
    CANSUPPORTIMAGES CANSUPPORTUSERID CANUPDATEPRESNAMEADDRESS CANUSEDESC CANUSERANGE CASESEN CHARTYPE
    CHE.PTTACCTID CHECKNUM CHGPINFIRST CHGUSERINFO CHKANDDEB CHKERROR CHKNUMEND CHKNUMSTART CHKSTATUS
    CITY CLIENTACTREQ CLIENTROUTING CLOSINGAVAIL CLTCOOKIE CODE COLNAME COLTYPE CONFMSG CONSUPOSTALCODE
    CORRECTACTION CORRECTFITID COUNT COUNTRY CREDITLIMIT CSPHONE CURDEF CURRATE CURSYM DATEBIRTH
    DAYPHONE DAYSTOPAY DAYSWITH DEBADJ DEPANDCREDIT DESC DETAILAVAILABLE DFLTDAYSTOPAY DIFFFIRSTPMT
    DIFFLASTPMT DOMXFERFEE DSCAMT DSCDATE DSCDESC DSCRATE DTACCTUP DTASOF DTAVAIL DTBILL DTCHANGED
    DTCLIENT DTCLOSE DTCREATED DTDUE DTDUEBY DTEFF DTEND DTEXPIRE DTINFOCHG DTNEXT DTOPEN DTPMTDUE
    DTPMTPRC DTPOSTED DTPOSTEND DTPOSTSTART DTPROFUP DTPURCHASE DTSEEN DTSERVER DTSTART DTUPDATE DTUSER
    DTXFERPRC DTXFERPRJ EMAIL EVEPHONE EXTDPMTCHK EXTDPMTCHK2 EXTDPMTDSC2 EXTDPMTFOR FAXPHONE FEE FEEMSG
    FICERTID FID FINALAMT FINAME FINCHG FIRSTNAME FITID FREQ FROM GENUSERKEY GETMIMESUP GROUPID
    HASEXTDPMT HASRECEXTDPMT HELPMESSAGE IDSCOPE IMAGEURL INCIMAGES INCLUDE INCLUDEBILLPMTSTATUS
    INCLUDEBILLSTATUS INCLUDECOUNTS INCLUDEDETAIL INCLUDESTATUSHIST INCLUDESUMMARY INITIALAMT
    INTLXFERFEE INVALIDACCTTYPE INVALIDACCTTYPE2 INVDATE INVDESC INVNO INVPAIDAMT INVTOTALAMT
    ITA.CAUSALE LANGUAGE LASTNAME LITMAMT LITMCODE LITMDESC LOGO LOSTSYNC MAILSUP MAX MEMO MEMO2 MESSAGE
    MESSAGE2 MIDDLENAME MIN MINAMTDUE MINPMTDUE MKTGINFO MODELWND MODPENDING N NAME NAMEACCTHELD
    NEEDTANPAYEE NEEDTANPMT NEEDTANTRANSFER NEWUSERPASS NINSTS NONCE NOTIFYDESIRED NOTIFYWILLING OFXSEC
    ONETIMEPASS ORG PAYACCT PAYANDCREDIT PAYEEID PAYEEID2 PAYEELSTID PAYEELSTID2 PAYEEMODPENDING
    PAYINSTRUCT PHONE PINCH PMTBYADDR PMTBYPAYEEID PMTBYXFER PMTFOR PMTINSTRUMENTTYPE PMTPRCCODE PMTTYPE
    POSTALCODE POSTPROCWND PREAUTH PREAUTHTOKEN PREFETCHURL PREVBAL PROCDAYSOFF PROCENDTM PURANDADV
    PWTYPE REASON RECSRVRTID RECSRVRTID2 REFNUM REFRESH REFRESHSUPT REJECTIFMISSING RESPFILEER RESTRICT
    SECURITYNAME SESSCOOKIE SEVERITY SIC SIGNONREALM SPACES SPECIAL SPNAME SRVRTID SRVRTID2 STATE
    STATUSMODBY STPCHKFEE STSVIAMODS SUBJECT SUPPORTDTAVAIL SUPTXDL SVC SVC2 SVCSTATUS SVCSTATUS2
    SYNCERROR SYNCMODE TABLENAME TAN TAXID TEMPPASS TO TOKEN TOKEN2 TOKENONLY TOTALFEES TOTALINT
    TRANSPSEC TRNAMT TRNTYPE TRNUID TSKEYEXPIRE TSPHONE URL URL2 URLGETREDIRECT USEHTML USERID USERKEY
    USERPASS VALIDATE VALUE VER XFERDAYSWITH XFERDEST XFERDFLTDAYSTOPAY XFERPRCCODE XFERSRC
    """.split()
)
